### ISSUE TITLE
stable releases?

### ISSUE THREAD

**Issue by davydden** [martemyev/tethex#1]
The [wiki](https://github.com/martemyev/tethex/wiki) implies

> tar -xf tethex-x.y.z-Source.tar.gz

that there are releases, but this is not the case. 

I see that this is a small project, but i think it would still be good to introduce at least `1.0` release. Also it would be good to state the requirement for `gmsh` version (if any).

**Comment by martemyev** [comment]
Hi Denis,

This project used to be hosted on GoogleCode, where I uploaded the archives of the sources in that `tethex-x.y.z-Source.tar.gz` format. The wiki was also written at that time. I'll update it.

As for the version of `gmsh` - as long as the input mesh is in ASCII 2.x format, tethex should be able to read it, so it's not quite related to the `gmsh` version.

Thanks,
Mikhail

**Comment by davydden** [comment]
> This project used to be hosted on GoogleCode, where I uploaded the archives of the sources in that tethex-x.y.z-Source.tar.gz format. The wiki was also written at that time. I'll update it.

I see... would you mind tagging releases here on GitHub, similar to what is done for deal.II: https://github.com/dealii/dealii/releases? 

I would like to add `tethex` to Spack package manager https://github.com/LLNL/spack to have under the same roof deal.II suite, Gmsh and this utility. To that end it would be better if your project has some releases.

**Comment by martemyev** [comment]
Hi Denis,

Please, check this out: http://github.com/martemyev/tethex/releases
Also, I updated the wiki.

Cheers,
Mikhail

**Comment by davydden** [comment]
great, thanks! see https://github.com/LLNL/spack/pull/1991
